src/Entity/Licence.php
<?php

namespace App\Entity;

use App\Repository\LicenceRepository;
use App\Service\LabelInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=LicenceRepository::class)
 */
class Licence implements LabelInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private string $name;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private string $acronym;

    /**
     * @ORM\OneToMany(targetEntity=Subscription::class, mappedBy="licence")
     */
    private Collection $subscriptions;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Regex("^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3}|[a-fA-F0-9]{8})$")
     */
    private ?string $color;

    public function __construct()
    {
        $this->subscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAcronym(): ?string
    {
        return $this->acronym;
    }

    public function getLabel(): ?string
    {
        return $this->acronym;
    }

    public function setAcronym(string $acronym): self
    {
        $this->acronym = $acronym;

        return $this;
    }

    /**
     * @return Collection|Subscription[]
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function addSubscription(Subscription $subscription): self
    {
        if (!$this->subscriptions->contains($subscription)) {
            $this->subscriptions[] = $subscription;
            $subscription->setLicence($this);
        }

        return $this;
    }

    public function removeSubscription(Subscription $subscription): self
    {
        $this->subscriptions->removeElement($subscription);
        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }
}

src/Entity/Subscriber.php
<?php

namespace App\Entity;

use App\Repository\SubscriberRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SubscriberRepository::class)
 */
class Subscriber
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private string $firstname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private string $lastname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private \DateTimeInterface $birthdate;

    /**
     * @ORM\Column(type="integer")
     */
    private int $licenceNumber;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private string $gender;

    public const GENDER = ['H' => 'Homme', 'F' => 'Femme'];

    /**
     * @ORM\OneToMany(targetEntity=Subscription::class, mappedBy="subscriber")
     */
    private Collection $subscriptions;

    public function __construct()
    {
        $this->subscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getLicenceNumber(): int
    {
        return $this->licenceNumber;
    }

    public function setLicenceNumber(int $licenceNumber): self
    {
        $this->licenceNumber = $licenceNumber;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection|Subscription[]
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function addSubscription(Subscription $subscriptions): self
    {
        if (!$this->subscriptions->contains($subscriptions)) {
            $this->subscriptions[] = $subscriptions;
            $subscriptions->setSubscriber($this);
        }

        return $this;
    }

    public function removeSubscription(Subscription $subscriptions): self
    {
        $this->subscriptions->removeElement($subscriptions);
        return $this;
    }
}

src/Controller/SubscriberController.php
<?php

namespace App\Controller;

use App\Entity\Filter;
use App\Entity\User;
use App\Form\FilterType;
use App\Repository\CategoryRepository;
use App\Repository\LicenceRepository;
use App\Repository\SeasonRepository;
use App\Repository\StatusRepository;
use App\Repository\SubscriberRepository;
use App\Service\Registration;
use Doctrine\ORM\EntityManagerInterface;
use App\Service\FirstSubscription;
use App\Service\SubscriptionDuration;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/adherents", name="subscribers_")
 */
class SubscriberController extends AbstractController
{
    private const PAGINATION_LIMIT = 50;

    /**
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     * @Route("/{display}/filtres/", name="filter")
     * @param string $display
     * @param Request $request
     * @param SubscriberRepository $subscriberRepository
     * @param SeasonRepository $seasonRepository
     * @param PaginatorInterface $paginator
     * @param EntityManagerInterface $entityManager
     * @param StatusRepository $statusRepository
     * @param LicenceRepository $licenceRepository
     * @param CategoryRepository $categoryRepository
     * @param FirstSubscription $firstSubscription
     * @param SubscriptionDuration $subscriptionDuration
     * @param Registration $registration
     * @return Response A response instance
     */
    public function filter(
        string $display,
        Request $request,
        SubscriberRepository $subscriberRepository,
        SeasonRepository $seasonRepository,
        PaginatorInterface $paginator,
        EntityManagerInterface $entityManager,
        StatusRepository $statusRepository,
        LicenceRepository $licenceRepository,
        CategoryRepository $categoryRepository,
        FirstSubscription $firstSubscription,
        SubscriptionDuration $subscriptionDuration,
        Registration $registration
    ): Response {
        $filter = new Filter();
        $user = $this->getUser();
        if (!is_null($user) && $user instanceof User && !is_null($user->getLastSearch())) {
            $lastSearch = unserialize($user->getLastSearch()[0], ['allowed_classes' => true]);
            $filter->hydrate(
                $lastSearch,
                $seasonRepository,
                $statusRepository,
                $licenceRepository,
                $categoryRepository
            );
        } else {
            $limitSeasons = SeasonRepository::LIMIT_NUMBER_SEASONS;
            $fromSeason = $seasonRepository->findBy([], ['id' => 'DESC'], $limitSeasons);
            $filter->setFromSeason($fromSeason[$limitSeasons - 1] ?? $seasonRepository->findOneBy([]));
            $filter->setToSeason($seasonRepository->findOneBy([], ['name' => 'DESC']));
        }
        $form = $this->createForm(FilterType::class, $filter, ['method' => 'GET']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $filters = $form->getData();
            $seasons = $seasonRepository->findByFilter($filters);
            $subscribersData = $subscriberRepository->findByFilter($filters);
            if (!empty($filter->getStatus())) {
                $subscribersData = $registration->filterWithSeasonAndWithStatus(
                    $subscribersData,
                    $filter->getStatus(),
                    $filter->getSeasonStatus()
                );
            }
            if (!empty($filter->getLicences())) {
                $subscribersData = $registration->filterWithSeasonAndWithLicence(
                    $subscribersData,
                    $filter->getLicences(),
                    $filter->getSeasonLicence()
                );
            }
            if (!empty($filter->getFromCategory()) || !empty($filter->getToCategory())) {
                $subscribersData = $registration->filterWithSeasonAndWithCategories(
                    $subscribersData,
                    $filter->getFromCategory(),
                    $filter->getToCategory(),
                    $filter->getSeasonCategory()
                );
            }
            if (!empty($filters->getFirstLicence())) {
                $subscribersData = $firstSubscription->filterWith(
                    $subscribersData,
                    $filters->getFirstLicence(),
                    $filters->isStillRegistered()
                );
            }
            if (!empty($filters->getFirstCategory())) {
                $subscribersData = $firstSubscription->filterWith(
                    $subscribersData,
                    $filters->getFirstCategory(),
                    $filters->isStillRegistered()
                );
            }
            if (!empty($filters->getDuration())) {
                $subscribersData = $subscriptionDuration->filterBy(
                    $subscribersData,
                    $filters->getDuration(),
                    $filters->isOrMore(),
                    $filters->isStillAdherent()
                );
            }
            $subscribers = $paginator->paginate(
                $subscribersData,
                $request->query->getint('page', 1),
                self::PAGINATION_LIMIT
            );

            $user instanceof User ? $user->setLastSearch((array)serialize($filters)) : false;
            $entityManager->flush();
            $numberResults = count($subscribersData);
            $categories = $categoryRepository->findAll();
            $categoriesDB = [];
            $key = '';
            foreach ($categories as $category) {
                if ($category->getColor() === $key) {
                    $categoriesDB[$key] .= ', ' . $category->getLabel();
                } else {
                    $key = $category->getColor();
                    $categoriesDB[$key] = $category->getOldGroup() . ' : ' . $category->getLabel();
                }
            }

            return $this->render('subscriber/index.html.twig', [
                'display' => $display,
                'subscribers' => $subscribers,
                'seasons' => $seasons,
                'filters' => $filters,
                'statusDB' => $statusRepository->findAll(),
                'categoriesDB' => $categoriesDB,
                'licencesDB' => $licenceRepository->findAllGroupByName(),
                'numberResults' => $numberResults
            ]);
        }

        return $this->render('subscriber/filter.html.twig', [
            'form' => $form->createView(),
            'display' => $display
        ]);
    }

    /**
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @Route("/export/{display}", name="export")
     * @param string $display
     * @param SubscriberRepository $subscriberRepository
     * @param SeasonRepository $seasonRepository
     * @param CategoryRepository $categoryRepository
     * @param LicenceRepository $licenceRepository
     * @return Response
     */
    public function export(
        string $display,
        SubscriberRepository $subscriberRepository,
        SeasonRepository $seasonRepository,
        CategoryRepository $categoryRepository,
        LicenceRepository $licenceRepository,
        FirstSubscription $firstSubscription,
        SubscriptionDuration $subscriptionDuration,
        StatusRepository $statusRepository,
        Registration $registration
    ) {
        $filters = new Filter();
        $user = $this->getUser();
        if (!is_null($user) && $user instanceof User && !is_null($user->getLastSearch())) {
            $lastSearch = unserialize($user->getLastSearch()[0], ['allowed_classes' => true]);
            $filters->hydrate(
                $lastSearch,
                $seasonRepository,
                $statusRepository,
                $licenceRepository,
                $categoryRepository
            );
        }

        $seasons = $seasonRepository->findByFilter($filters);
        $subscribers = $subscriberRepository->findByFilter($filters);

        if (!empty($filters->getFirstLicence())) {
            $subscribers = $firstSubscription->filterWith(
                $subscribers,
                $filters->getFirstLicence(),
                $filters->isStillRegistered()
            );
        }
        if (!empty($filters->getFirstCategory())) {
            $subscribers = $firstSubscription->filterWith(
                $subscribers,
                $filters->getFirstCategory(),
                $filters->isStillRegistered()
            );
        }
        if (!empty($filters->getDuration())) {
            $subscribers = $subscriptionDuration->filterBy(
                $subscribers,
                $filters->getDuration(),
                $filters->isOrMore(),
                $filters->isStillAdherent()
            );
        }

        if (!empty($filters->getStatus())) {
            $subscribers = $registration->filterWithSeasonAndWithStatus(
                $subscribers,
                $filters->getStatus(),
                $filters->getSeasonStatus()
            );
        }
        if (!empty($filters->getLicences())) {
            $subscribers = $registration->filterWithSeasonAndWithLicence(
                $subscribers,
                $filters->getLicences(),
                $filters->getSeasonLicence()
            );
        }
        if (!empty($filters->getFromCategory()) || !empty($filters->getToCategory())) {
            $subscribers = $registration->filterWithSeasonAndWithCategories(
                $subscribers,
                $filters->getFromCategory(),
                $filters->getToCategory(),

templates/subscriber/export.csv.twig
N LICENCE;PRENOM;NOM;DATE DE NAISSANCE;GENRE{% for season in seasons %};{{ season.name }}{% endfor %};
{% for subscriber in subscribers -%}
    {{- subscriber.licenceNumber }};{{ subscriber.firstname|raw }};{{ subscriber.lastname|raw }};{{ subscriber.birthdate|date("m/d/Y") }};{{- subscriber.gender -}};
    {%- for season in seasons -%}
    {%- for subscription in subscriber.subscriptions|filter(subscription => subscription.season.id == season.id) -%}
        {%- if display == 'licences' -%}
                {{- subscription.licence.acronym -}};
        {%- elseif display == 'inscriptions' -%}
                {{- subscription.category.label -}};
        {%- elseif display == 'renouvellements' -%}
                {{- subscription.status.label -}};
        {%- endif -%}
        {%- else -%}
        {{- ' ' -}};
    {%- endfor -%}
    {%- endfor %}

{% endfor %}

templates/subscriber/filter.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ parent() }} Récapitulatifs - Filtres{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('filter') }}
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <h1 class="text-center mt-4 mb-2">Récapitulatif des {{ display }}</h1>
        <h2 class="text-center mb-4">Filtres de sélection</h2>
        {{ form_start(form) }}
        {{ form_errors(form) }}
        <div class="row ml-5 justify-content-between">
            <div class="col-4">
                <h2 class="title-filter ml-2 my-3">Saison</h2>
                <div class="filter-group pb-2 pt-4 pl-4 w-80">
                    {{ form_row(form.fromSeason) }}
                    {{ form_row(form.toSeason) }}
                </div>
            </div>
            <div class="col-4">
                <h2 class="title-filter ml-2 my-3">Numéro adhérent</h2>
                <div class="filter-group pb-2 pt-4 pl-4 w-80">
                    {{ form_row(form.fromAdherent) }}
                    {{ form_row(form.toAdherent) }}
                </div>
            </div>
            <div class="col-2 filter-gender">
                <h2 class="title-filter ml-2 my-3">Sexe</h2>
                <div class="filter-group pb-2 pt-4 pl-4 w-80">
                    {{ form_row(form.gender) }}
                </div>
            </div>
        </div>
        <div class="row mt-1 ml-5">
            <div class="col-6">
                <h2 class="title-filter ml-2 my-3">Catégorie</h2>
                <div class="filter-group pb-2 pt-4 pl-4 d-flex justify-content-between align-items-center">
                    <div class="w-50">
                        <div>
                            {{ form_row(form.fromCategory) }}
                        </div>
                        <div>
                            {{ form_row(form.toCategory) }}
                        </div>
                    </div>
                    <div class="mx-4">
                        {{ form_row(form.seasonCategory) }}
                    </div>
                </div>
            </div>
            <div class="col-6">
                <h2 class="title-filter ml-2 my-3">Première inscription</h2>
                <div class="filter-group pb-2 pt-4 pl-4 w-90 d-flex flex-row justify-content-between align-items-center">
                    <div class="w-50">
                        <div>
                            {{ form_row(form.firstLicence) }}
                        </div>
                        <div>
                            {{ form_row(form.firstCategory) }}
                        </div>
                    </div>
                    <div class="d-flex align-items-center mr-4">
                        {{ form_row(form.stillRegistered) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-1 ml-5">
            <div class="col-6">
                <h2 class="title-filter ml-2 my-3">Type de licence</h2>
                <div class="filter-group pb-2 pt-4 pl-4 d-flex justify-content-between">
                    <div class="d-flex align-items-center">
                        {{ form_row(form.licences) }}
                    </div>
                    <div class="mr-4">
                        {{ form_row(form.seasonLicence) }}
                    </div>
                </div>
            </div>
            <div class="col-6">
                <h2 class="title-filter my-3">Durée d'inscription</h2>
                <div class="filter-group pb-2 pt-4 pl-4 w-90 d-flex flex-row justify-content-between">
                    <div class="d-flex flex-row">
                        <div class="duration">
                            {{ form_row(form.duration) }}
                        </div>
                        <div class="d-flex align-items-center">
                            {{ form_row(form.orMore) }}
                        </div>
                    </div>
                    <div class="d-flex align-items-center mr-4">
                        {{ form_row(form.stillAdherent) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-1 mb-2 ml-5">
            <div class="col-7">
                <h2 class="title-filter ml-2 my-3">Statut</h2>
                <div class="filter-group pb-2 pt-4 pl-4 d-flex flex-row justify-content-between">
                    <div class="d-flex align-items-center">
                        {{ form_row(form.status) }}
                    </div>
                    <div class="mr-4">
                        {{ form_row(form.seasonStatus) }}
                    </div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary my-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-check2"
                 viewBox="0 0 16 16">
                <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5
                10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
            </svg>
            Appliquer
        </button>
        <a href="{{ path('subscribers_reinitialisation', {display : display}) }}" class="btn btn-primary my-3 ml-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-arrow-counterclockwise" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 3a5 5 0 1 1-4.546 2.914.5.5 0 0 0-.908-.417A6 6 0 1 0 8 2v1z"/>
                <path d="M8 4.466V.534a.25.25 0 0 0-.41-.192L5.23 2.308a.25.25 0 0 0 0 .384l2.36 1.966A.25.25 0 0 0 8 4.466z"/>
            </svg>
            Réinitialiser
        </a>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/subscriber/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} Récapitulatif des {{ display }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1 class="text-center my-4">Récapitulatif des {{ display }}</h1>
        <div class="mb-4 filters">
            <h2 class="h3 pt-3 pb-2 text-center">Filtres appliqués</h2>
            <div class="row px-4 pt-4">
                <div class="col-3 pb-4">
                    Saisons : de <strong>{{ filters.fromSeason.name }}</strong>
                    à <strong>{{ filters.toSeason.name }}</strong>
                </div>
                {% if filters.fromAdherent or filters.toAdherent %}
                    <div class="col-3 pb-4">
                        Numéro adhérent : de <strong>{{ filters.fromAdherent ? filters.fromAdherent : '-' }}</strong>
                        à <strong>{{ filters.toAdherent ? filters.toAdherent : '-' }}</strong>
                    </div>
                {% endif %}
                {% if filters.gender|length == 1 %}
                    <div class="col-2 pb-4">
                        Sexe : <strong>{{ constant('App\\Entity\\Subscriber::GENDER')[filters.gender[0]] }}</strong>
                    </div>
                {% endif %}
                {% if filters.fromCategory or filters.toCategory %}
                    <div class="col-4 pb-4">
                        Catégorie : de <strong>{{ filters.fromCategory ? filters.fromCategory.label : '-' }}</strong>
                        à <strong>{{ filters.toCategory ? filters.toCategory.label : '-' }}</strong>
                        (pour la saison <strong>{{ filters.seasonCategory.name }}</strong>)
                    </div>
                {% endif %}
                {% if filters.firstLicence or filters.firstCategory %}
                    <div class="col-6 pb-4">
                        Première inscription en :
                        <strong>
                            {{ filters.firstLicence ? filters.firstLicence.acronym : filters.firstCategory.label }}
                        </strong>
                        {{ filters.stillRegistered ? 'et toujours inscrit' : '' }}
                    </div>
                {% endif %}
                {% if filters.duration %}
                    <div class="col-4 pb-4">
                        Durée d'inscription :
                        <strong>{{ filters.duration }}</strong> an(s)
                        <strong>{{ filters.orMore ? 'ou plus' : '' }}</strong>
                        {{ filters.stillAdherent ? 'et toujours inscrit' : '' }}
                    </div>
                {% endif %}
            </div>
            <div class="row pb-4 pl-4">
                {% if filters.status %}
                    <div class="col-6">
                        Statut :
                        {% set status = '' %}
                        {% for filter in filters.status %}
                            {% set status = loop.last ? status ~ filter.name : status ~ filter.name ~ ', ' %}
                        {% endfor %}
                        <strong>{{ status }}</strong>
                        (pour la saison <strong>{{ filters.seasonStatus.name }}</strong>)
                    </div>
                {% endif %}
                {% if filters.licences %}
                    <div class="col-6">
                        Type de licence :
                        {% set licences = '' %}
                        {% for licence in filters.licences %}
                            {% set licences =
                                loop.last ? licences ~ licence.acronym : licences ~ licence.acronym ~ ', ' %}
                        {% endfor %}
                        <strong>{{ licences }}</strong>
                        (pour la saison <strong>{{ filters.seasonLicence.name }}</strong>)
                    </div>
                {% endif %}
            </div>
            <div class="text-center filters">
                <a href="{{ path('subscribers_filter', {display : display}) }}" type="button" class="btn btn-primary mb-4">
                    Faire une nouvelle recherche
                </a>
            </div>
        </div>
        <div class="row mb-3 mr-1 justify-content-end align-items-center">
            {% if display == 'renouvellements' %}
                Statuts :
                {% for status in statusDB %}
                    <div class="p-1 ml-2" style="background-color: {{ status.color }};">
                        {{ status.name }}
                    </div>
                {% endfor %}
            {% endif %}
            {% if display == 'inscriptions' %}
                Catégories :
                {% for color, category in categoriesDB %}
                    <div class="p-1 ml-2" style="background-color: {{ color }};">
                        {{ category }}
                    </div>
                {% endfor %}
            {% endif %}
            {% if display == 'licences' %}
                Types de licences :
                {% for licence in licencesDB %}
                    <div class="p-1 ml-2" style="background-color: {{ licence.color }};">
                        {{ licence.name }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-hover table-striped table-sm">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">N° adhérent</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Prénom</th>
                        <th scope="col">Date de naissance</th>
                        <th scope="col">Genre</th>
                        {% for season in seasons %}
                            <th scope="col" class="text-center">{{ season.name }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for subscriber in subscribers %}
                        <tr>
                            <td>{{ subscriber.licenceNumber}}</td>
                            <td>{{ subscriber.lastname }}</td>
                            <td>{{ subscriber.firstname }}</td>
                            <td>{{ subscriber.birthdate|date("d/m/Y") }}</td>
                            <td>{{ subscriber.gender }}</td>
                            {% for season in seasons %}
                                {% for subscription in subscriber.subscriptions|filter(subscription => subscription.season.id == season.id) %}
                                    {% if display == 'licences' %}
                                        <td class="text-center" style="background-color:{{ subscription.licence.color }}">{{ subscription.licence.acronym }}</td>
                                    {% elseif display == 'renouvellements'%}
                                        <td class="text-center" style="background-color:{{ subscription.status.color ?? ''}} ">{{ subscription.status.label ?? '?'}}</td>
                                    {% elseif display == 'inscriptions' %}
                                        <td class="text-center" style="background-color:{{ subscription.category.color }}">{{ subscription.category.label ?? 'null' }}</td>
                                    {% endif %}
                                {% else %}
                                    <td></td>
                                {% endfor %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-center align-items-start">
                    <nav aria-label="pagination">
                        {% do subscribers.setPageRange(3) %}
                        {{ knp_pagination_render(subscribers,
                            '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig',
                            {},
                            {
                                'align': 'center',
                            })
                        }}
                    </nav>
                    <div class="mt-2 mr-4 results">{{ numberResults }} résultat(s)</div>
                </div>
                <div class="row">
                    <div class="col">
                        <a href="{{ path('subscribers_export', {display : display}) }}" class="btn btn-sm btn-primary mt-3 mb-5">Exporter en csv</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}